# Generated by Django 4.0.2 on 2022-02-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authenticationcustomuser_delete_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
