# Generated by Django 4.0.2 on 2022-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
