# Generated by Django 4.0.2 on 2022-02-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
        migrations.AddField(
            model_name='customuser',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
